### ISSUE TITLE
hi, Does this model need 2 GPU to run?

### ISSUE THREAD

**Issue by bitwangdan** [zhihou7/VCL#1]
Does one GPU work?

**Comment by zhihou7** [comment]
Sorry for getting back to you late. 
emmm, My code just uses one GPU in fact. I tried to use 2 GPU. But I suffer from a wired bug ([here](https://github.com/tensorflow/tensorflow/issues/32836)). According to my experiment, the more instances each batch has, the better result we can achieve. It is because we can compose more HOIs in each batch.

**Comment by zhihou7** [comment]
All the results are based on one GPU. But I still keep the code for two GPUs because I hope someone could fix [the bug](https://github.com/tensorflow/tensorflow/issues/32836).

**Comment by bitwangdan** [comment]
@zhihou7 
hi, In section 4.6 of the Paper, You used t-SNE to show the results，Can you share the code for the T-SNE network?
thanks!

**Comment by zhihou7** [comment]
@bitwangdan 
hi, scripts/extract_HO_feature.py  and scripts/feats_tsne.py provide the code of t-SNE figure. It has been in this project

**Comment by bitwangdan** [comment]
> @bitwangdan
> hi, scripts/extract_HO_feature.py and scripts/feats_tsne.py provide the code of t-SNE figure. It has been in this project

thanks!
